"""Primitive geometric operations for Lloyd V4."""

from .directional_alpha_probe import (
    ALPHA_PROBE_CONSUMER_PROTOCOL,
    ALPHA_PROBE_SPACE,
    DIRECTIONAL_ALPHA_PROBE_PROTOCOL,
    AlphaProbeObservation,
    AlphaProbeResult,
    DeclaredAlphaModel,
    directional_alpha_probe,
)
from .scalar_alpha_jet_bundle import (
    SCALAR_ALPHA_JET_BUNDLE_CONSUMER_PROTOCOL,
    SCALAR_ALPHA_JET_BUNDLE_PROTOCOL,
    SCALAR_ALPHA_JET_BUNDLE_SPACE,
    ScalarAlphaJetBundleObservation,
    ScalarAlphaJetBundleResult,
    scalar_alpha_jet_bundle,
)
from .singular_alpha_jet_bundle import (
    SINGULAR_ALPHA_JET_BUNDLE_CONSUMER_PROTOCOL,
    SINGULAR_ALPHA_JET_BUNDLE_PROTOCOL,
    SINGULAR_ALPHA_JET_BUNDLE_SPACE,
    SingularAlphaJetBundleObservation,
    SingularAlphaJetBundleResult,
    singular_alpha_jet_bundle,
)
from .typed_collection import (
    NON_EMPTY_TYPED_COLLECTION_PROTOCOL,
    TYPED_COLLECTION_PROTOCOL,
    TypedCollectionResult,
    TypedCollectionValue,
    typed_collection,
)
from .typed_value import (
    NON_NULL_TYPED_VALUE_PROTOCOL,
    TYPED_VALUE_PROTOCOL,
    TypedValueResult,
    TypedValueValue,
    typed_value,
)
from .projective_ratio import (
    PROJECTIVE_RATIO_PROTOCOL,
    PROJECTIVE_RATIO_SCALARIZATION_PROTOCOL,
    PROJECTIVE_RATIO_SCALARIZATION_TRANSITION_RULE,
    ProjectiveRatioResult,
    ProjectiveRatioValue,
    projective_ratio,
    scalarize_projective_ratio,
)
from .typed_finite_difference import (
    TRANSFER_OBSERVATION_CONSUMER_PROTOCOL,
    TRANSFER_SPACE,
    TYPED_FINITE_DIFFERENCE_PROTOCOL,
    TransferObservation,
    TransferObservationResult,
    typed_finite_difference,
)
from .typed_log_log_slope import (
    LOG_LOG_SLOPE_CONSUMER_PROTOCOL,
    LOG_LOG_SLOPE_SPACE,
    TYPED_LOG_LOG_SLOPE_PROTOCOL,
    LogLogSlopeObservation,
    LogLogSlopeResult,
    typed_log_log_slope,
)
from .stratified_quadratic_roots import (
    QUADRATIC_ROOT_SELECTION_PROTOCOL,
    QUADRATIC_ROOT_SELECTION_TRANSITION_RULE,
    STRATIFIED_QUADRATIC_ROOTS_PROTOCOL,
    QuadraticCoefficients,
    QuadraticRootCoordinate,
    QuadraticRootStateResult,
    StratifiedQuadraticRootValue,
    select_quadratic_root,
    stratified_quadratic_roots,
)

__all__ = [
    "ALPHA_PROBE_CONSUMER_PROTOCOL",
    "ALPHA_PROBE_SPACE",
    "AlphaProbeObservation",
    "AlphaProbeResult",
    "DIRECTIONAL_ALPHA_PROBE_PROTOCOL",
    "DeclaredAlphaModel",
    "NON_EMPTY_TYPED_COLLECTION_PROTOCOL",
    "NON_NULL_TYPED_VALUE_PROTOCOL",
    "LOG_LOG_SLOPE_CONSUMER_PROTOCOL",
    "LOG_LOG_SLOPE_SPACE",
    "LogLogSlopeObservation",
    "LogLogSlopeResult",
    "PROJECTIVE_RATIO_PROTOCOL",
    "PROJECTIVE_RATIO_SCALARIZATION_PROTOCOL",
    "PROJECTIVE_RATIO_SCALARIZATION_TRANSITION_RULE",
    "ProjectiveRatioResult",
    "ProjectiveRatioValue",
    "QUADRATIC_ROOT_SELECTION_PROTOCOL",
    "QUADRATIC_ROOT_SELECTION_TRANSITION_RULE",
    "SCALAR_ALPHA_JET_BUNDLE_CONSUMER_PROTOCOL",
    "SCALAR_ALPHA_JET_BUNDLE_PROTOCOL",
    "SCALAR_ALPHA_JET_BUNDLE_SPACE",
    "SINGULAR_ALPHA_JET_BUNDLE_CONSUMER_PROTOCOL",
    "SINGULAR_ALPHA_JET_BUNDLE_PROTOCOL",
    "SINGULAR_ALPHA_JET_BUNDLE_SPACE",
    "STRATIFIED_QUADRATIC_ROOTS_PROTOCOL",
    "ScalarAlphaJetBundleObservation",
    "ScalarAlphaJetBundleResult",
    "SingularAlphaJetBundleObservation",
    "SingularAlphaJetBundleResult",
    "TYPED_COLLECTION_PROTOCOL",
    "TYPED_FINITE_DIFFERENCE_PROTOCOL",
    "TYPED_LOG_LOG_SLOPE_PROTOCOL",
    "TYPED_VALUE_PROTOCOL",
    "QuadraticCoefficients",
    "QuadraticRootCoordinate",
    "QuadraticRootStateResult",
    "StratifiedQuadraticRootValue",
    "TRANSFER_OBSERVATION_CONSUMER_PROTOCOL",
    "TRANSFER_SPACE",
    "TransferObservation",
    "TransferObservationResult",
    "TypedCollectionResult",
    "TypedCollectionValue",
    "TypedValueResult",
    "TypedValueValue",
    "directional_alpha_probe",
    "projective_ratio",
    "scalar_alpha_jet_bundle",
    "scalarize_projective_ratio",
    "select_quadratic_root",
    "singular_alpha_jet_bundle",
    "stratified_quadratic_roots",
    "typed_collection",
    "typed_finite_difference",
    "typed_log_log_slope",
    "typed_value",
]
